GET http://localhost:5000/api/adc/0

###

GET http://localhost:5000/api/mcp3008/0

###

GET http://localhost:5000/api/digital/22

###

PUT http://localhost:5000/api/digital
Content-Type: application/json

{"pin": 27, "value": true}

###

GET http://localhost:5000/api/pwm_duty/0

###

PUT http://localhost:5000/api/pwm_duty
Content-Type: application/json

{"pin": 3, "value": 35.5}

###

GET http://localhost:5000/api/info
