GET http://localhost:5000/api/hello

###

GET http://localhost:5000/test/read_analog

###

GET http://localhost:5000/test/digital_high

###

GET http://localhost:5000/test/digital_low

###

GET http://localhost:5000/test/read_temperature

###

GET http://localhost:5000/test/pwm_duty_none

###

GET http://localhost:5000/test/pwm_duty_half

###

GET http://localhost:5000/test/pwm_duty_full

###

POST http://localhost:5000/api/target_temperature
Content-Type: application/json

{"target_temperature": 30}

###

GET http://localhost:5000/api/current_temperature
